version: '3'

services:
  broker-service:
    build:
      context: C:\github\dockergo\go-microservice\broker-service
      dockerfile: C:\github\dockergo\go-microservice\broker-service\broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - backend

  authentication-service:
    build:
      context: C:\github\dockergo\go-microservice\authentication-service
      dockerfile: C:\github\dockergo\go-microservice\authentication-service\authentication-service.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    networks:
      - backend

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
